services:
  server:
    container_name: interstellar-server
    build:
      context: ./ # Update this to the actual path of your backend server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - interstellar-network
    environment:
      - MONGODB_URI=${MONGODB_URI:?error}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:?error}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SERVER_API_BASE_URL=${SERVER_API_BASE_URL:?error}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - PORT=${PORT}

networks:
  interstellar-network:
    driver: bridge
